config/routes.rb
CoderetreatApp::Application.routes.draw do
  resources :coderetreats, only: [] do
    get :running_today, :on => :collection

    #get :edit_status, :on => :member
    #put :update_status, :on => :member

    resource :status, controller: 'status', only: [:edit, :update]
  end
end

app/models/coderetreat.rb
require 'coderetreats/statuses'

class Coderetreat < ActiveRecord::Base
  def self.running_today
    all
  end

  def available_next_statuses
    CoderetreatApp::Coderetreats::Statuses.all - [self.status]
  end

  def update_status(new_status)
    self.update_attributes status: new_status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coderetreats_controller.rb
require 'coderetreats'
require 'coderetreats/status'

class CoderetreatsController < ApplicationController
  def running_today   
    @coderetreats = CoderetreatApp::Coderetreats.running_today
  end
end

app/controllers/status_controller.rb
require 'coderetreats/status'

class StatusController < ApplicationController
  def edit
    @coderetreat = Coderetreat.find(coderetreat_id)
  end

  def update
    CoderetreatApp::Coderetreats::Status.update_to(coderetreat_id, coderetreat_params[:new_status])
    redirect_to edit_coderetreat_status_url(coderetreat_id)
  end

private
  def coderetreat_id
    params[:coderetreat_id]
  end

  def coderetreat_params
    params.permit(:new_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coderetreats_helper.rb
module CoderetreatsHelper
end

app/views/coderetreats/edit_status.html.haml
%h2 Edit the status for #{@coderetreat.location}

=form_for @coderetreat, url: update_status_coderetreat_path(@coderetreat, new_status: "in_session"), method: "put" do |f| 
  =f.submit "Start Session"

=form_for @coderetreat, url: update_status_coderetreat_path(@coderetreat, new_status: "on_break"), method: "put" do |f| 
  =f.submit "Start Break"

app/views/coderetreats/running_today.html.haml
%h2 There are no coderetreats running today.

- @coderetreats.grouped_by_status do |status, coderetreats|
  %section.coderetreats{"class" => status}
    %header
      %h2= status.titleize
      %ul
        - coderetreats.each do |coderetreat|
          %li.coderetreat= coderetreat.location

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderetreatApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/status/edit.html.haml
%h2 Edit the status for #{@coderetreat.location}

-@coderetreat.available_next_statuses.each do |status|

  =form_for @coderetreat, url: coderetreat_status_path(@coderetreat, new_status: status), method: "put" do |f| 
    =f.submit status.titleize